# Remap prefix from 'C-b' to 'C-a'.
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pane resizing keybinds.
bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R

# Fix Esc delay in Neovim.
set -sg escape-time 0

# Set shell
set -g default-shell /bin/zsh

# Set the name to 256color.
set -g default-terminal 'tmux-256color'
set-option -a terminal-features 'xterm-256color:RGB'

# Start count at 1, since zero in somewhere else entirely on the keyboard.
set -g base-index 1

# Enable Vi mode.
set-window-option -g mode-keys vi

# Use XTerm keybindings.
set-window-option -g xterm-keys on
set -g terminal-overrides "xterm*:kLFT5=\eOD:kRIT5=\eOC:kUP5=\eOA:kDN5=\eOB:smkx@:rmkx@"

set-option -s set-clipboard on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se c -i"

set-option -g set-titles on
set-option -g set-titles-string "Tmux - #{session_name}"

# Make the split shortkeys more sensible.
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Enable mouse mode.
set -g mouse on
set -g @yank_with_mouse off

# Reload config with 'r'.
bind r source-file ~/.tmux.conf\; display-message "Config reload"

# Vim-like pane switching.
bind k selectp -U
bind j selectp -D
bind h selectp -L
bind l selectp -R


# Silence the terminal bell.
set -g bell-action none
set -g visual-bell off

# Colours.
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=white bg=colour238 bold'

# Pane colours.
set -g pane-border-style 'fg=colour245 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour15'

# Status bar colours.
set -g status-position bottom
set -g status-justify centre
set -g status-style 'fg=colour137'
set -g status-left ''
set -g status-right ''
set -g status-right-length 50
set -g status-left-length 20
set -g status-interval 1

# Status bar.
setw -g window-status-current-style 'fg=colour255 bg=colour0 bold'
setw -g window-status-current-format '#[fg=colour240]#[bg=colour240] #[fg=colour255]#I#[fg=colour249]:#[fg=colour255]#W#[fg=colour240]#F#[bg=colour238]#[fg=colour238]#[fg=colour255,bg=colour238] %d-%m-%Y #[fg=colour240,bg=colour238]#[fg=colour255,bg=colour240] %H:%M:%S #[fg=colour240,bg=default]'

setw -g window-status-style 'fg=colour7 bg=colour242'
setw -g window-status-format '#[bg=colour0]#[fg=colour242]#[bg=colour242]#[fg=colour255] #I#[fg=colour254]:#[fg=colour255]#W#[fg=colour242]#F#[bg=colour0]'

setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

# Message colours.
set -g message-style 'fg=colour255 bg=colour22 bold'

set -g focus-events on

# Load some TMUX plugins.
set -g @plugin 'christoomey/vim-tmux-navigator'

# Run the TMUX plugins.
run '~/.tmux/plugins/tpm/tpm'
